name: Lint and Clippy
on:
  push:
    paths:
      - '**/'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize submodules
      run: git submodule update --recursive --init
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: fmt
      uses: actions-rs/cargo@v1
      continue-on-error: false
      with:
        command: fmt
        args: --all -- --check
    - name: clippy
      uses: actions-rs/cargo@v1
      continue-on-error: false
      with:
        command: clippy
        args: -- -D warnings